spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account_route
          uri: http://localhost:8081
          predicates:
            - Path=/accounts/**
        - id: transaction_route
          uri: http://localhost:8082
          predicates:
            - Path=/transactions/**

