spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        spring.json.trusted.packages: "com.anurag.order.orderservice.entity.Order"
      group-id: myGroup
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false
server:
  port: 8082
