server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        spring.json.trusted.packages: "com.anurag.bank.transaction.entity"
      group-id: myGroup
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false


